server:
  port: 8069

spring:
  application:
    name: FDS-Spring
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.sql

currency-tracker:
  cb-api-url: "https://www.cbr-xml-daily.ru/daily_json.js"

